name: release published

on:
  release:
    types:
      - published

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        env:
          EVENT: ${{ github.event }}
        run: echo $EVENT
