name: release edited

on:
  release:
    types:
      - edited

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check
      env:
        EVENT: ${{ github.event }}
        run: echo $EVENT
