name: release prereleased

on:
  release:
    types:
      - prereleased

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check
      env:
        EVENT: ${{ github.event }}
        run: echo $EVENT
