name: release unpublished

on:
  release:
    types:
      - unpublished

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        env:
          EVENT: ${{ github.event }}
        run: echo $EVENT
